### ISSUE TITLE
Suggestion: Russian Translation of the Mod

### ISSUE THREAD

**Issue by electrovoyage** [Rabbitminers/Extended-Flywheels#1]
Hello. I recently found this mod on curseforge, and saw that there isnt a Russian translation (at least on the page). I tried to message you on Discord, but the message could not be delivered. My mother tongue is Russian, so i figure i could translate the mod. Plus, the modpage says it was made with MCreator, so i figure importing and exporting the translations won't be too hard. Feel free to contact me at artemplay0607@gmail.com! (most of the time i check my emails daily!)

**Comment by Rabbitminers** [comment]
Hello! I've sent you an email with the language file for you to translate when your able to
