### ISSUE TITLE
ja_jp become ru_ru in 1.18.2 0.5.e

### ISSUE THREAD

**Issue by Omokage-R** [Rabbitminers/Extended-Flywheels#10]
The contents of the ja_jp is ru_ru's one in 1.18.2 0.5.e.
When I change language to Japanese ,it becomes Russian because the file is actually ru_ru.
Please replace ja_jp to actual ja_jp file.

**Comment by Rabbitminers** [comment]
The translations have been fixed and will be in the next release. thanks for reporting it
