### ISSUE TITLE
Create Deployers Crafting no works using extended cogs

### ISSUE THREAD

**Issue by SrRapero720** [Rabbitminers/Extended-Flywheels#18]
Crafting some items like Precission mechanism no works if i use extended cogwheels
![image](https://user-images.githubusercontent.com/29090346/215180261-182f7d10-5690-4369-b931-ecab9cbff266.png)

**Comment by Rabbitminers** [comment]
Ah that's a bit of an oversight. Ill get to working on a patch. In the meantime there's a backup recipe to convert other cogwheels to the default ones which should hopefully still work

**Comment by Rabbitminers** [comment]
Patched In Mulitloader Beta
