### ISSUE TITLE
V 1.19.2 | LootTable 

### ISSUE THREAD

**Issue by Pidizzel** [Rabbitminers/Extended-Flywheels#19]
Describe the Bug
As soon as I start my server these errors come up in the console.

[main/ERROR] [minecraft/LootTables]: Couldn't parse loot table extendedgears:blocks/brass_cogwheel
[minecraft/LootTables]: Couldn't parse loot table extendedgears:blocks/large_brass_cogwheel

Reproduction Steps
1. starting server
2. see console

Crash Report or Log
https://pastebin.com/9hTQWNtc

Operating System
Windows 10

Mod Version
0.5.0i

Minecraft Version
1.19.2

Forge Version
43.2.4

Other Mods
[Mod Liste.txt] (https://github.com/Creators-of-Create/Create/files/10610579/Mod.Liste.txt)

Additional Context
auch in anderen Versionen

**Comment by Rabbitminers** [comment]
Patched In Latest Beta Release
