### ISSUE TITLE
Breaking particles for flywheels of this mod mismatched

### ISSUE THREAD

**Issue by electrovoyage** [Rabbitminers/Extended-Flywheels#2]
I just found that flywheels from this mod (or at least Crimson Plated) have mismatched particle textures:
![bug](https://user-images.githubusercontent.com/75689188/188197406-66ce5c64-7853-42e5-a644-c09eeeac9ef5.png)
Instead of an appropriate texture it uses the one for default Create Brass flywheels. This isnt anything critical by any means, but fixing this could be a quality of life improvement.

**Comment by Rabbitminers** [comment]
Ah I forgot to add this to the asset generation for block states, ill patch this soon

**Comment by electrovoyage** [comment]
Alright. As i said, this is more of a QoL improvement, so it's not necessary.

**Comment by Rabbitminers** [comment]
Fixed Issue in latest patch, all flywheels now use a related particle
