### ISSUE TITLE
Extended Cogwheels 1.19.2 makes recipes from the create mod invalid

### ISSUE THREAD

**Issue by yoyo7043** [Rabbitminers/Extended-Flywheels#23]
The examples I've come across are removing the stick from the wrench recipe and making the precision mechanism uncraftable due to the iron nugget being replaced with something invalid
![Capture](https://user-images.githubusercontent.com/36887096/228375095-04de0013-bcea-41c6-aac7-bd48c3a72e0d.PNG)

**Comment by yoyo7043** [comment]
wrong image XD
![Capture](https://user-images.githubusercontent.com/36887096/228375031-032b79de-5a1d-4e1b-8db6-7fa5dcf960fb.PNG)

**Comment by drwoops** [comment]
please, attend to this bug.  it is one of the most frequently reported issue in the create discord.

**Comment by drwoops** [comment]
dang! the link for extended cogwheels issues points here, which is the wrong project!
