### ISSUE TITLE
Shaftless cogwheels are able to be used in recipes with cogwheels

### ISSUE THREAD

**Issue by PablloOswalld** [Rabbitminers/Extended-Flywheels#24]
Maybe this isnt even an issue and is intended with the mod but ive found that the mod allows to use the Shaftless cogwheels (that are made with only wood and no need for andesite alloy/shafts) which maybe doesnt really makes sense or at least makes thing a tad more cheap than they should be, maybe i should just be using a mod that would fix this particular issue? no clue, tried checkin if maybe this could be disabled/enabled on the configs but found nothing.

**Comment by Rabbitminers** [comment]
This is an intentional feature
