### ISSUE TITLE
Precision Mechanism

### ISSUE THREAD

**Issue by jojoblackFr** [Rabbitminers/Extended-Flywheels#28]
A bug replace the iron nugget in the recipe to a invalid item
(1.19.2 fabric)

**Comment by PaternoX** [comment]
same issue. cant create precision mechanisms due to invalid step 3 (fabric 1.19.2)

**Comment by Rabbitminers** [comment]
I'm guessing this is meant for Extended Cogwheels. This has been patched for the next release
