### ISSUE TITLE
Copper Cogs are missing recipies

### ISSUE THREAD

**Issue by SpiderKolo** [Rabbitminers/Extended-Flywheels#29]
I was checking out this mod as I was experimenting with my new modpack that I wanted to make with Create... and I realized that Copper Cogs from this add-on don't have recipe.
Specifically: Small and Big ones with whole shaft in them have no recipies for them and ones with half and none shafts do contain the cutting recipe, but are also missing the initial crafting ones you could maybe perform on crafting table/mechanical crafters.

**Comment by DoxLePup** [comment]
The crafting recipe for the Copper cog is just one shaft and one copper ingot. then the bigger one is copper ingot with the small cog.  also the non-shaft copper cog is a copper ingot with a copper nugget
