### ISSUE TITLE
[Log] Reference map 'steampowered.refmap.json' for extendedflywheels.mixins.json could not be read.

### ISSUE THREAD

**Issue by Lucky-56** [Rabbitminers/Extended-Flywheels#3]
`Reference map 'steampowered.refmap.json' for extendedflywheels.mixins.json could not be read. If this is a development environment you can ignore this message`
appears at startup, assuming I'm not in a 'dev environment' this shouldn't happen

**Forge:** 43.1.47
**Mod Version:** 1.2.2

**Comment by Rabbitminers** [comment]
Patched In Mulitloader Port
