### ISSUE TITLE
encased cogwheel doesnt drop anything when broken

### ISSUE THREAD

**Issue by DoxLePup** [Rabbitminers/Extended-Flywheels#30]
Cogs can now be encased however when breaking a "encased cogwheel" it doesnt drop anything. Also ive noticed in creative that block-picking the created encased cogwheel just gives you a cogwheel, not an encased cogwheel. Work around being that the wrench is able to pick it up just fine.
There is also another bug that is when you do exactly what I just mentioned, a shaftless cog is given a shaft, with no shaft needed. so you can make cogs with wood alone and then encase them (for free since encasing doesnt use up the andesite casing) it is then turned into a full cogwheel with shaft.

_Originally posted by @DoxLePup in https://github.com/Rabbitminers/Extended-Flywheels/issues/16#issuecomment-1534118231_

**Comment by Rabbitminers** [comment]
Closed as duplicate
