### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by DannieAvocado** [Rabbitminers/Extended-Flywheels#33]
I'm not sure if it's me, but it keeps having this error on the latest version of Create. Unless it me, can you help this Issue?

**Comment by Tesver50** [comment]
What are your mods and forge version

**Comment by DannieAvocado** [comment]
I am using mostly all Create mods (Enchantment industry, Crafts and Additions Deco, Etc.) and some other ones like Dynamic lights, sound. Framed blocks, that one backpack mod from Rlcraft and other mods, and my forge version is 43.2.3,

**Comment by Tesver50** [comment]
do you have mods like EF or EC or create steam & rails or some other create addons that didn't receive an update since the realease of create 5.1 ?

**Comment by DannieAvocado** [comment]
Yes, Extended Cogwheels and Flywheels were the problem I wanted to fix. Everything is up to date and working. Ext cog/fly were the only ones having the error.

**Comment by SpottyTheTurtle** [comment]
Neither extended flywheels nor extended cogwheels have been updated to work with 0.5.1 yet

**Comment by DannieAvocado** [comment]
Ah okay, thank you for helping anyways!

**Comment by P4YN-Ki** [comment]
Any information on when EC and EF will be updated to work with Create 0.5.1a ?

**Comment by Tesver50** [comment]
as EC and EF are made to work on fabric AND forge they will be updated once create 5.1 gets out for fabric

**Comment by P4YN-Ki** [comment]
Thanks for the quick reply. It's a shame, but since Create Fabric is 2 whole versions behind, I'm guessing the update isn't going to be coming any time soon.

**Comment by SpottyTheTurtle** [comment]
On the contrary, they're scheduled to release within a few days.

**Comment by P4YN-Ki** [comment]
Seriously? Thanks for the update on that! Everything has fallen apart the last 2 weeks. Create updates and everything stops working, curseforge issues with the malware and then certain pages not opening, finally ATLauncher is removing some curseforge links (Steam'n'Rails can only be goten from modrinth now)...... Anyway sorry to keep pulling you here. Thanks for the update, much appreciated.
