### ISSUE TITLE
crash on start up with create 5.1 (1.19.2)

### ISSUE THREAD

**Issue by crystalgem1** [Rabbitminers/Extended-Flywheels#38]
If i start the mod with the newest version if create in 1.19.2 i just get an failed on start up error (filed to load correctly), which is a shame since i wanted to use the different stress capacitys from the cogwheels for my modpack

[latest.log](https://github.com/Rabbitminers/Extended-Flywheels/files/12044971/latest.log)

**Comment by SpottyTheTurtle** [comment]
downgrade Create to 0.5.1b

**Comment by crystalgem1** [comment]
sure i can do that for now but, will you ever update it so it works for the newest versions?

update, sadly your mod doesnt seam to work with any 5.1 version of create, let me know if there is something in the making or if you just need time / a break
