### ISSUE TITLE
[Suggestion] future support and less log spam (flip-v)

### ISSUE THREAD

**Issue by Lucky-56** [Rabbitminers/Extended-Flywheels#4]
Log: `Model "extendedflywheels:block/bluesteelflywheel/block" is using the deprecated "flip-v" field in its OBJ model instead of "flip_v". This field will be removed in 1.20.`
just change the field I guess

**Forge:** 43.1.47
**Mod Version:** 1.2.2

**Comment by lexxieblack** [comment]
This really needs fixing, the spam is absurd.

**Comment by Rabbitminers** [comment]
This will  be fixed in the next patch for 1.19.2

**Comment by Rabbitminers** [comment]
This issue should be fixed in the latest patch
