### ISSUE TITLE
compatability with mods that allow extream customisable blocks like chisle and bits

### ISSUE THREAD

**Issue by mobbymobslayer** [Rabbitminers/Extended-Flywheels#40]
i first thought this was a bug but after doing some looking in configs i noticed since the adition of configurable files regarding the immovable blocks other moded blocks like custom chisel and bits "chiselled rock" witch is also classed as an immovable block are no longer compatible with creations and ive seen a fue complaints on the chisel and bits page about this issue however the issue appears to only occur beyond create 0.5.0i witch was before the implication changes regarding immovable objects from what i can see comparing config files

**Comment by Rabbitminers** [comment]
This is more to do with Create that Extended Flywheels, perhaps try asking here https://github.com/Creators-of-Create/Create/issues

**Comment by mobbymobslayer** [comment]
ok thanks
